# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('team_logo', models.ImageField(upload_to='teams/logos/')),
            ],
        ),
    ]
