# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1)),
                ('bets', models.IntegerField(default=0)),
                ('bet_type', models.CharField(choices=[('1', 'first'), ('X', 'draw'), ('2', 'second')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(choices=[('asd', 'asd')], max_length=1)),
                ('second_team', models.CharField(choices=[('asd', 'asd')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Match'),
        ),
    ]
