# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181010_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_betted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='money_bet',
            field=models.IntegerField(default=0, max_length=250),
        ),
    ]
