# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181014_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='money_bet',
            field=models.IntegerField(default=0),
        ),
    ]
