# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 16:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_userbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbank',
            name='user_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
