# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20181111_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='bet_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Match'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserBank'),
        ),
    ]
