# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20181111_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbet',
            name='bet_users',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
