# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181111_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.UserBank'),
        ),
    ]
