# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20181111_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_users',
        ),
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserBank'),
        ),
    ]
