# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_userbet_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='is_betted',
        ),
        migrations.AddField(
            model_name='bet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
