# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20181125_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='bet_id',
            field=models.IntegerField(default=0),
        ),
    ]
