# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20181202_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
