# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 12:26
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20181202_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='bet_status',
            field=models.CharField(choices=[('1', 'win'), ('X', 'pending'), ('0', 'lost')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='money_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='money_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
