# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 16:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20181202_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='money_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='money_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
